logo: BountyHacker # add logo name
title: BountyHacker - Index
description: > # this means to ignore newlines until "baseurl:"
  Esta es una descripcion genial de mi web
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: background.jpg # add banner video. Add your video file to the folder video
banner-title: root@BountyHacker:~# # add banner title
banner-desc: The quieter you become, the more you are able to hear. # add banner description

# Author settings
author-pic: logo.jpg # your photo
author-name: Thomas Emerson Glucklich # your name
about-author: Ingeniero de Ciberseguridad DevSecOps # about author
email: thomas-emerson@live.com # your email
phone: (+)569666***** # your pnone number
website: https://bountyhacking.github.io/ # you website

# Social link
youtube_url: https://www.youtube.com/channel/UChNTj2xNpEQiliMv-IJbWvQ
github_url: https://github.com/bountyhacking/
instagram_url: https://youtube.com/shorts/9O9lRpm-0sg?feature=share # add url link
linkedin_url: https://www.linkedin.com/in/thomyemerson/

# Disqus
discus_identifier: mr-brown # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: https://disqus.com/admin/create/

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]